# Generated by Django 5.0.2 on 2024-02-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailFinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200)),
            ],
        ),
    ]
