# Generated by Django 5.0.2 on 2024-02-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailFinder', '0003_remove_emailmodel_email_emailmodel_emails'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_list', models.TextField()),
                ('emails', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailModel',
        ),
        migrations.DeleteModel(
            name='WebsiteModel',
        ),
    ]
