# Generated by Django 5.0.2 on 2024-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailFinder', '0004_findermodel_delete_emailmodel_delete_websitemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True)),
            ],
        ),
    ]
